
runtime: python38
# threadsafe is required but can be either true or 
# false. For some package, it should be true e.g. Flask
#threadsafe: true
#api_version: 1

handlers:


- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: code.py

